name: Bring Back release PR

on:
  push:
    branches:
      - develop

jobs:
  create-branch:
    if: startsWith(github.event.before, 'refs/heads/release/')  # Run this job only if the branch that triggered the event was a release/** branch.
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from Release Branch
        id: extract_version
        run: |
          echo "Event before: ${{ github.event.before }}"
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" EggTimer/Info.plist)
          echo "Version: $VERSION" 
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Setup developer details
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"    
    
      - name: Create New Version Branch
        run: |
          NEW_BRANCH="adhoc/bring_back_release_${{ env.version }}"
          git checkout -b ${NEW_BRANCH}
          git push origin ${NEW_BRANCH}

      - name: Create pull request to staging branch
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @- https://api.github.com/repos/${{ github.repository }}/pulls <<EOF
          {
            "title": "Release version ${{ env.VERSION }} to staging",
            "head": ${NEW_BRANCH},
            "base": "staging",
            "body": "This PR is automatically created from the release branch ${{ github.ref }}."
          }
          EOF
